// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfPEMYKlF6cMc9ZbMfWLThSY4FtO3SXTE',
    appId: '1:673865577680:web:227a3f43b6921eedd61ad5',
    messagingSenderId: '673865577680',
    projectId: 'shafa-25',
    authDomain: 'shafa-25.firebaseapp.com',
    storageBucket: 'shafa-25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPpA12gYMeBYU3HGUgDOHrQ8mS1JpeFFU',
    appId: '1:673865577680:android:90691bc3b1c9d67bd61ad5',
    messagingSenderId: '673865577680',
    projectId: 'shafa-25',
    storageBucket: 'shafa-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9V1I4KbTe_CReWL9-Q8rfxz-uy3vfkU',
    appId: '1:673865577680:ios:2d450a986b9843a0d61ad5',
    messagingSenderId: '673865577680',
    projectId: 'shafa-25',
    storageBucket: 'shafa-25.firebasestorage.app',
    iosBundleId: 'com.example.shafa25Birthday',
  );
}
