name: Flutter Web Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'  # Specify Flutter version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Copy Favicon (Ensure it is included in the build)
      - name: Copy favicon to web directory
        run: cp web/favicon.png web/favicon.ico web/index.html build/web/ || true

      # Step 5: Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release --base-href="/shafa-25-birthday/"

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use your PAT here
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web